### ISSUE TITLE
create Helm v2 charts

### ISSUE THREAD

**Issue by rimusz** [buildkite/charts#8]

**Comment by bendrucker** [comment]
Hi, I'm interested in working on this and #9. I got stuck this morning when I realized that these charts are for an earlier version of Helm. I'm quite new to k8s and migrating our buildkite agents into a cluster is my first trial project. Will take a stab at the upgrade this afternoon if I can, otherwise sometime this week!

Thanks again for all your work here! I've been thoroughly impressed with the depth and quality of the third party tools in the k8s ecosystem, especially compared to the other orchestrator offerings! 
👍 👍 🙏

**Comment by rimusz** [comment]
I have done separate charts for AWS and Google cloud, they just need to be merged together to make one single chart, but got stuck with so many things, so wasn't able to find time to finish merge.

**Comment by rimusz** [comment]
@bendrucker I will dedicate some of my cycles tomorrow to make it done.

**Comment by bendrucker** [comment]
Oh, lovely! I see now that there's a v2 branch, I'll try to mess around with that until you find time.

**Comment by rimusz** [comment]
i created that branch today, will finish it tomorrow

**Comment by rimusz** [comment]
made one universal chart, closing this issue

**Comment by bendrucker** [comment]
Awesome I'll give this a spin today

**Comment by rimusz** [comment]
fighting with github pages permissions, does not allow to download files with helm/curl :(

**Comment by bendrucker** [comment]
Hmm, I'm able to do this: `curl https://buildkite.github.io/charts/index.yaml`. I'll try actually installing  via helm with the remote repo in a bit.
